name: Publish node package

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-packages/npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install
        run: npm ci
      #- name: Publish
      #  run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v2.2.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          registry: https://npm.pkg.github.com/
